"""bookmarks timestamp eklendi

Revision ID: 8f25e11b884b
Revises: 1f2f2ed0375b
Create Date: 2025-12-25 14:39:42.061854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f25e11b884b'
down_revision = '1f2f2ed0375b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
